### ISSUE TITLE
Detail and scope 1.0.0 issues

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt#3370]
We want to look through all the v1.0.0 tagged issues and:

1. Have a description of what the work entails
1. Have a discussion on that work amongst the team
1. Scope out each item and prioritize it

Below are the issues, their assigned person, and the day we would like to present 

### June 2nd
- [x] [Rework standard installation experience](https://github.com/fishtown-analytics/dbt/issues/3361) - @gshank 
- [x] [Execute-only invocations](https://github.com/fishtown-analytics/dbt/issues/3360) - @iknox-fa 
- [x] [Stabilize structured logging](https://github.com/fishtown-analytics/dbt/issues/3359) - @kwigley 
- [x] [Remove the distinction between --select and --models flags when working with node types](https://github.com/fishtown-analytics/dbt/issues/3210) - @nathaniel-may 

### June 9th
- [x] [Move starter project for init task into dbt repo](https://github.com/fishtown-analytics/dbt/issues/3005) - @gshank 
- [x] [More consistency for global CLI flags](https://github.com/fishtown-analytics/dbt/issues/2990) - @iknox-fa 
- [x] [Parity for source freshness task/command](https://github.com/fishtown-analytics/dbt/issues/2987) - @kwigley 
- [x] [Rationalize quoting configs + properties](https://github.com/fishtown-analytics/dbt/issues/2986) - @nathaniel-may 

### June 24th
- [x] [Make default test-paths and analysis-paths configs consistent](https://github.com/fishtown-analytics/dbt/issues/2659) - @gshank 
- [x] [Allow data tests to be documented](https://github.com/fishtown-analytics/dbt/issues/2578) - @iknox-fa 
- [x] [Remove ingestion-time partitioned tables in BigQuery and all associated logic](https://github.com/fishtown-analytics/dbt/issues/2332) - @kwigley 
- [x] [Give profiles some love](https://github.com/fishtown-analytics/dbt/issues/1958) - @nathaniel-may 

### July 1st 
- [x] [Remove agate dependency?](https://github.com/fishtown-analytics/dbt/issues/3413) - @gshank   
- [x] [Enact deprecations](https://github.com/fishtown-analytics/dbt/issues/2798) - @nathaniel-may 

### July 8th
- [x] [Add an alias for source-paths configuration key](https://github.com/fishtown-analytics/dbt/issues/1607) - @iknox-fa
- [x] [Better node IDs](https://github.com/fishtown-analytics/dbt/issues/3348) - @nathaniel-may 
- [x] [Split RPC server into separate codebase](https://github.com/dbt-labs/dbt/issues/3501) - @kwigley 
- [x] [Turn on perf improvements by default](https://github.com/dbt-labs/dbt/issues/3502) - @gshank

**Comment by leahwicz** [comment]
We want to look through all the v1.0.0 tagged issues and:

1. Have a description of what the work entails
1. Have a discussion on that work amongst the team
1. Scope out each item and prioritize it

Below are the issues, their assigned person, and the day we would like to present 

### May 26th
- [ ] [Rework standard installation experience](https://github.com/fishtown-analytics/dbt/issues/3361)
- [ ] [Execute-only invocations](https://github.com/fishtown-analytics/dbt/issues/3360)
- [ ] [Stabilize structured logging](https://github.com/fishtown-analytics/dbt/issues/3359)
- [ ] [Remove the distinction between --select and --models flags when working with node types](https://github.com/fishtown-analytics/dbt/issues/3210)

### June 2nd

### June 9th

### June 16th

**Comment by leahwicz** [comment]
@jtcohen6 if there are any more items to add to the list or any items that don't need scoped please feel free to adjust the list accordingly before I start assigning people to topics

**Comment by jtcohen6** [comment]
@leahwicz That list looks great to me! I gather that we're leaving off #2743 and #2401, because those are ones we've already discussed in some detail and which we know to be quite complex.

**Comment by leahwicz** [comment]
@jtcohen6 yeah I left them off since we are planning to work on them this cycle (#2743 for sure) so the scoping will happen no matter what
