### ISSUE TITLE
[Tracking] Experimental Parser (Tree Sitter)

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt#3377]
## Proof of Concept (Completed 04/20/21)

- [x]  [Write tree-sitter grammar for subset of jinja and unit test.](https://github.com/fishtown-analytics/dbt/issues/3215)
- [x]  [Extract refs sources and configs from model file.](https://github.com/fishtown-analytics/dbt/issues/3215)
- [x]  Detect false positives and misses with sample projects- both must be zero.
- [x]  Determine if the percent of model files affected is worth it to include in the main product. (result = 60%)

## 0.20.0-RC1  (Completed 05/20/21)

- [x]  [dbt with the experimental parser passes unit tests](https://github.com/fishtown-analytics/dbt/issues/3306)
- [x]  [Run internal analytics project with and without the experimental parser. Manifest files must compare as exactly the same.](https://github.com/fishtown-analytics/dbt/issues/3306)
- [x] [dbt with the experimental parser passes integration tests](https://github.com/fishtown-analytics/dbt/issues/3306)
- [x]  [Make a packaging strategy for the new parser + dbt.](https://github.com/fishtown-analytics/dbt/issues/3307)
- [x]  Split tree-sitter repository from extractor
- [x]  [Create separate CI pipeline for tree-sitter repository to create wheels and upload to pypi ](https://github.com/fishtown-analytics/dbt/issues/3307)(Thank you, Kyle!)
- [x]  Rerun integration tests once the tree-sitter dependency is installable from pypi.
- [x]  [Add `--use-experimental-parser` flag to core, defaulting to false.](https://github.com/fishtown-analytics/dbt/issues/3307)

## 0.20.0-RC2 (Completed 06/29/21)
- [x] rewrite extractor and tests in rust. ([PR](https://github.com/fishtown-analytics/dbt-parser-generator/pull/12))
- [x] write PyO3 wrapper to expose to python ABI (https://github.com/fishtown-analytics/dbt-parser-generator/issues/19)
- [x] depend on tree-sitter-jinja2 not via private repo branch (publish on crates.io, or public repo (easiest)
- [x] add github actions to package extractor (https://github.com/fishtown-analytics/dbt-parser-generator/issues/18)
- [x] add step to publish to pypi to github actions (https://github.com/fishtown-analytics/dbt-parser-generator/issues/18)
- [x] rerun project test runner with rust extractor (https://github.com/fishtown-analytics/dbt-parser-generator/issues/20)
- [x] in dbt remove extractor.py, both tree-sitter dependencies, and instead depend on the rust extractor package from pypi [PR](https://github.com/fishtown-analytics/dbt/pull/3497)

## 0.20.0

- [x]  Add snowplow reporting to sometimes run both and send back if they match or not. (https://github.com/fishtown-analytics/dbt/issues/3503)
- [x]  Add counter for how many model files were "experimentally parsed" vs "jinja rendered" to the perf file. (https://github.com/fishtown-analytics/dbt/issues/3438)
- [x]  Add snowplow reporting to track how many models can be parsed without jinja rendering. (https://github.com/fishtown-analytics/dbt/issues/3438)

## Before flag is on by default

- [x]  Rewrite extractor in Rust for type safety and confidence in making future changes. Will need to decide to keep Rust code in the dbt repository, or depend on the extractor as an outside library. (Went with outside library)
- [x]  Make sure the experimental parser can detect when ref source or config has been overridden with a macro and can skip everything instead of running. New test for this necessary. Hard prereq for turning on by default.
- [ ] Apply feedback from beta testers.
- N/A  ~Work with Experience and Platform teams to create and execute a beta-testing plan with the `--use-experimental-parser` flag.~ This is no longer necessary with the current structure of the flag and tracking.
