### ISSUE TITLE
[Tracking] `dbt build` command

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt#3452]
Tracking issue for the generalized `dbt build` command outlined in issue https://github.com/fishtown-analytics/dbt/issues/2743

- [x] [RAT](https://github.com/fishtown-analytics/dbt/issues/3415)
- [x] Demo
- [x] Ensure produced artifacts (`manifest.json`, `run_results.json`, `sources.json`) make sense
- [ ] #3597
- [x] Exclude `source snapshot-freshness` for now
- [ ] #3596
- [ ] #3595
- [x] Additional resource types (~1 left)
- [x] #3598

~~ - [ ] Refactor cmd line library ~~ --> still a smart thing to do, but not needed for this effort

**Comment by jtcohen6** [comment]
> Parity for flags

Ideal is that `build` supports the superset of all flags. If a flag is supported by any one of the sub-tasks, it should be supported by `build`, too. Tasks that can use the flag, observe it; tasks that can't use it, ignore it.

> Ensure produced artifacts (run_results.json + sources.json) make sense

Should `dbt build` also include `dbt docs generate` (and produce `catalog.json` as well)? This one is funny, I'd want to think

**Comment by jtcohen6** [comment]
I'm going to close this tracking issue, in favor of keeping #3595, #3596, #3597 open and tagged for the next cycle epic + release milestone. In the future, let's open all tracking issues as epics, which enables us to nest an epic for a specific work-area (e.g. `dbt build`) inside larger release + cycle epics.
