### ISSUE TITLE
[Tracking] v0.19.2 final release 

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt#3504]
### Release Core
- [x] [Engineering] dbt-release workflow 
- [x] [Engineering] Create new protected `x.latest` branch 
- [ ] ~[Product] Finalize migration guide (next.docs.getdbt.com)~

### Release Cloud
- [x] [Engineering] Create a platform issue to update dbt Cloud and verify it is completed https://github.com/fishtown-analytics/dbt-cloud/issues/3366
- [x] [Engineering] Determine if schemas have changed. If so, generate new schemas and push to schemas.getdbt.com

### Announce
- [ ] ~[Product] Publish discourse~
- [x] [Product] Announce in dbt Slack

### Post-release
- [x] [Engineering] Bump plugin versions (dbt-spark + dbt-presto), add compatibility as needed
   - [x]  Spark 
   - [x]  Presto
- [x] [Engineering] Create a platform issue to update dbt-spark versions to dbt Cloud 
- [ ] ~[Product] Release new version of dbt-utils with new dbt version compatibility. If there are breaking changes requiring a minor version, plan upgrades of other packages that depend on dbt-utils.~
- [x] [Engineering] If this isn't a final release, create an epic for the next release
