### ISSUE TITLE
[Tracking] v0.20.1rc1 release

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3569]
### Release Core
- [x] [Engineering] [dbt-release workflow](https://www.notion.so/dbtlabs/Releasing-b97c5ea9a02949e79e81db3566bbc8ef#03ff37da697d4d8ba63d24fae1bfa817) 
- ~[Engineering] Create new protected `x.latest` branch~
- ~[Product] Finalize migration guide (next.docs.getdbt.com)~

### Release Cloud
- [x] [Engineering] Create a platform issue to update dbt Cloud and verify it is completed. [Example issue](https://github.com/dbt-labs/dbt-cloud/issues/3481)
- ~[Engineering] Determine if schemas have changed. If so, generate new schemas and push to schemas.getdbt.com~

### Announce
- [ ] ~[Product] Publish discourse~
- [x] ~[Product] Announce in dbt Slack~

### Post-release
- [x] [Engineering] [Bump plugin versions](https://www.notion.so/dbtlabs/Releasing-b97c5ea9a02949e79e81db3566bbc8ef#f01854e8da3641179fbcbe505bdf515c) (dbt-spark + dbt-presto), add compatibility as needed
   - [x]  Spark 
   - [x]  Presto
- [x] [Engineering] Create a platform issue to update dbt-spark versions to dbt Cloud. [Example issue](https://github.com/dbt-labs/dbt-cloud/issues/3481)
- ~[ ] [Product] Release new version of dbt-utils with new dbt version compatibility. If there are breaking changes requiring a minor version, plan upgrades of other packages that depend on dbt-utils.~
- [ ] [Engineering] If this isn't a final release, create an epic for the next release
